### ISSUE TITLE
Compilation error w/ TypeScript 3.2.2

### ISSUE THREAD

**Issue by jcfranco** [dojo/framework#205]
**Bug**

To reproduce, clone https://github.com/dojo/examples and update TS from any of the examples to the latest and compile. You'll get an error like the following:

```
/Users/jcfranco/projects/dojo-examples/todo-mvc/node_modules/typescript/lib/tsc.js:71026
throw e;
^

RangeError: Maximum call stack size exceeded
at resolveNameHelper (/Users/jcfranco/projects/dojo-examples/todo-mvc/node_modules/typescript/lib/tsc.js:26029:35)
at resolveName (/Users/jcfranco/projects/dojo-examples/todo-mvc/node_modules/typescript/lib/tsc.js:26027:20)
at resolveEntityName (/Users/jcfranco/projects/dojo-examples/todo-mvc/node_modules/typescript/lib/tsc.js:26721:26)
at resolveTypeReferenceName (/Users/jcfranco/projects/dojo-examples/todo-mvc/node_modules/typescript/lib/tsc.js:31878:20)
at getTypeFromTypeReference (/Users/jcfranco/projects/dojo-examples/todo-mvc/node_modules/typescript/lib/tsc.js:32054:30)
at getTypeFromTypeNode (/Users/jcfranco/projects/dojo-examples/todo-mvc/node_modules/typescript/lib/tsc.js:33414:28)
at getConstraintFromTypeParameter (/Users/jcfranco/projects/dojo-examples/todo-mvc/node_modules/typescript/lib/tsc.js:31740:72)
at fillMissingTypeArguments (/Users/jcfranco/projects/dojo-examples/todo-mvc/node_modules/typescript/lib/tsc.js:31330:49)
at getTypeFromClassOrInterfaceReference (/Users/jcfranco/projects/dojo-examples/todo-mvc/node_modules/typescript/lib/tsc.js:31830:78)
at getTypeReferenceTypeWorker (/Users/jcfranco/projects/dojo-examples/todo-mvc/node_modules/typescript/lib/tsc.js:31943:24)
```

IMO, this is a serious issue since it prevents using `@dojo/framework` in any project using the latest TS version. 

**Note**: I did not test with other versions.

**Comment by agubler** [comment]
@jcfranco Hi thanks for reporting this, we try hard to be forwards compatible as best as we can for TypeScript versions and for the next major release (5.0.0) we have tested up to 3.1. TypeScript 3.2 was only released 15 days ago and looks to have included some breaking changes, which causes your error.

We will investigate this and if possible we'll update dojo to support TypeScript 3.2 in the upcoming release.

**Comment by matt-gadd** [comment]
@sebilasse we support typescript `2.6.2` through to `3.1.0`
